name: Build & Deploy

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10.13.0
    - name: Build & Deploy
      run: |
        yarn
        yarn build
        yarn add firebase-tools
        npx firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
      env:
        CI: true
        REACT_APP_FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
